export const contributionModes = [
  { id: 'monthly', label: 'Monthly' },
  { id: 'yearly', label: 'Yearly' },
  { id: 'none', label: 'None' },
];

export const instrumentTemplates = {
  epf: {
    type: 'epf',
    name: 'EPF',
    category: 'Retirement',
    currentValue: 450000,
    contribution: 216000,
    contributionMode: 'yearly',
    expectedReturn: 8.15,
    lockInYears: 30,
    salaryAnnual: 1500000,
    salaryGrowth: 7,
    employerContributionRate: 3.67,
  },
  nps: {
    type: 'nps',
    name: 'NPS',
    category: 'Retirement',
    currentValue: 250000,
    contribution: 5000,
    contributionMode: 'monthly',
    expectedReturn: 9,
    lockInYears: 25,
  },
  ppf: {
    type: 'ppf',
    name: 'PPF',
    category: 'Fixed Income',
    currentValue: 180000,
    contribution: 150000,
    contributionMode: 'yearly',
    expectedReturn: 7.1,
    lockInYears: 15,
  },
  lic: {
    type: 'lic',
    name: 'LIC Policy',
    category: 'Insurance',
    currentValue: 300000,
    contribution: 60000,
    contributionMode: 'yearly',
    expectedReturn: 5.5,
    lockInYears: 20,
  },
  savings: {
    type: 'savings',
    name: 'Bank Savings',
    category: 'Cash',
    currentValue: 250000,
    contribution: 10000,
    contributionMode: 'monthly',
    expectedReturn: 3.5,
    lockInYears: 0,
  },
  fd: {
    type: 'fd',
    name: 'Fixed Deposit',
    category: 'Fixed Income',
    currentValue: 500000,
    contribution: 0,
    contributionMode: 'none',
    expectedReturn: 7,
    lockInYears: 5,
  },
  sukanya: {
    type: 'sukanya',
    name: 'Sukanya Samriddhi',
    category: 'Goals',
    currentValue: 100000,
    contribution: 120000,
    contributionMode: 'yearly',
    expectedReturn: 8.2,
    lockInYears: 21,
  },
  mutual_fund: {
    type: 'mutual_fund',
    name: 'Mutual Funds',
    category: 'Market Linked',
    currentValue: 700000,
    contribution: 20000,
    contributionMode: 'monthly',
    expectedReturn: 12,
    lockInYears: 0,
  },
  stocks: {
    type: 'stocks',
    name: 'Stocks',
    category: 'Market Linked',
    currentValue: 350000,
    contribution: 50000,
    contributionMode: 'yearly',
    expectedReturn: 13,
    lockInYears: 0,
  },
  gratuity: {
    type: 'gratuity',
    name: 'Gratuity',
    category: 'Retirement',
    currentValue: 0,
    contribution: 0,
    contributionMode: 'none',
    expectedReturn: 0,
    lockInYears: 5,
    salaryAnnual: 1500000,
    salaryGrowth: 7,
    yearsOfService: 6,
  },
};

export const scenarioPresets = {
  conservative: {
    label: 'Conservative',
    returns: { epf: 8.15, nps: 8, ppf: 7.1, lic: 5, savings: 3, fd: 6.5, sukanya: 8, mutual_fund: 9, stocks: 10, gratuity: 0 },
  },
  moderate: {
    label: 'Moderate',
    returns: { epf: 8.15, nps: 9, ppf: 7.1, lic: 5.5, savings: 3.5, fd: 7, sukanya: 8.2, mutual_fund: 12, stocks: 13, gratuity: 0 },
  },
  aggressive: {
    label: 'Aggressive',
    returns: { epf: 8.15, nps: 10.5, ppf: 7.1, lic: 6, savings: 4, fd: 7.25, sukanya: 8.2, mutual_fund: 15, stocks: 16, gratuity: 0 },
  },
};

export const sampleInvestments = [
  { ...instrumentTemplates.epf, id: crypto.randomUUID(), contribution: 216000 },
  { ...instrumentTemplates.mutual_fund, id: crypto.randomUUID(), contribution: 20000 },
  { ...instrumentTemplates.ppf, id: crypto.randomUUID(), contribution: 150000 },
  { ...instrumentTemplates.fd, id: crypto.randomUUID(), currentValue: 500000 },
  { ...instrumentTemplates.gratuity, id: crypto.randomUUID() },
];
