export const contributionModes = [
  { id: 'monthly', label: 'Monthly' },
  { id: 'yearly', label: 'Yearly' },
  { id: 'none', label: 'None' },
];

export const instrumentTemplates = {
  epf: {
    type: 'epf',
    name: 'EPF',
    category: 'Retirement',
    currentValue: 1837505,
    contribution: 33000,
    contributionMode: 'monthly',
    expectedReturn: 8.15,
    lockInYears: 30,
    currentAge: 33,
    maturityAge: 58,
    maxContributionYears: 25,
    salaryAnnual: 1500000,
    salaryGrowth: 7,
    employerContributionRate: 0,
    epsMonthlyContribution: 1250,
    epsSalaryCapMonthly: 15000,
    epsPensionableSalaryMonthly: 15000,
    epsYearsOfService: 6,
    epsPensionAge: 58,
    epsEarlyPensionAge: 50,
    epsMinimumPension: 1000,
  },
  nps: {
    type: 'nps',
    name: 'NPS',
    category: 'Retirement',
    currentValue: 250000,
    contribution: 5000,
    contributionMode: 'monthly',
    expectedReturn: 9,
    lockInYears: 25,
    currentAge: 33,
    maturityAge: 60,
    maxContributionYears: 27,
  },
  ppf: {
    type: 'ppf',
    name: 'PPF',
    category: 'Fixed Income',
    currentValue: 180000,
    contribution: 150000,
    contributionMode: 'yearly',
    expectedReturn: 7.1,
    lockInYears: 15,
    currentAge: 33,
    maturityAge: 48,
    maxContributionYears: 15,
  },
  lic: {
    type: 'lic',
    name: 'LIC Policy',
    category: 'Insurance',
    currentValue: 300000,
    contribution: 60000,
    contributionMode: 'yearly',
    expectedReturn: 5.5,
    lockInYears: 20,
    currentAge: 33,
    maturityAge: 53,
    maxContributionYears: 20,
  },
  savings: {
    type: 'savings',
    name: 'Bank Savings',
    category: 'Cash',
    currentValue: 250000,
    contribution: 10000,
    contributionMode: 'monthly',
    expectedReturn: 3.5,
    lockInYears: 0,
    currentAge: 33,
    maturityAge: 90,
    maxContributionYears: 57,
  },
  fd: {
    type: 'fd',
    name: 'Fixed Deposit',
    category: 'Fixed Income',
    currentValue: 500000,
    contribution: 0,
    contributionMode: 'none',
    expectedReturn: 7,
    lockInYears: 5,
    currentAge: 33,
    maturityAge: 38,
    maxContributionYears: 0,
  },
  sukanya: {
    type: 'sukanya',
    name: 'Sukanya Samriddhi',
    category: 'Goals',
    currentValue: 100000,
    contribution: 120000,
    contributionMode: 'yearly',
    expectedReturn: 8.2,
    lockInYears: 21,
    currentAge: 7,
    maturityAge: 21,
    maxContributionYears: 8,
  },
  mutual_fund: {
    type: 'mutual_fund',
    name: 'Mutual Funds',
    category: 'Market Linked',
    currentValue: 700000,
    contribution: 20000,
    contributionMode: 'monthly',
    expectedReturn: 12,
    lockInYears: 0,
    currentAge: 33,
    maturityAge: 90,
    maxContributionYears: 57,
  },
  stocks: {
    type: 'stocks',
    name: 'Stocks',
    category: 'Market Linked',
    currentValue: 350000,
    contribution: 50000,
    contributionMode: 'yearly',
    expectedReturn: 13,
    lockInYears: 0,
    currentAge: 33,
    maturityAge: 90,
    maxContributionYears: 57,
  },
  etf: {
    type: 'etf',
    name: 'ETFs',
    category: 'Market Linked',
    currentValue: 250000,
    contribution: 10000,
    contributionMode: 'monthly',
    expectedReturn: 11,
    lockInYears: 0,
    currentAge: 33,
    maturityAge: 90,
    maxContributionYears: 57,
  },
  real_estate_plot: {
    type: 'real_estate_plot',
    name: 'Real Estate Plot',
    category: 'Real Estate',
    currentValue: 2500000,
    contribution: 0,
    contributionMode: 'none',
    expectedReturn: 8,
    lockInYears: 3,
    currentAge: 33,
    maturityAge: 90,
    maxContributionYears: 0,
  },
  real_estate_flat: {
    type: 'real_estate_flat',
    name: 'Flat / Apartment',
    category: 'Real Estate',
    currentValue: 6000000,
    contribution: 0,
    contributionMode: 'none',
    expectedReturn: 6,
    lockInYears: 5,
    currentAge: 33,
    maturityAge: 90,
    maxContributionYears: 57,
    rentAnnual: 240000,
    rentGrowth: 5,
    rentalYieldReinvestRate: 5,
  },
  rent_income: {
    type: 'rent_income',
    name: 'Rent Income Corpus',
    category: 'Cashflow',
    currentValue: 0,
    contribution: 0,
    contributionMode: 'none',
    expectedReturn: 5,
    lockInYears: 0,
    currentAge: 33,
    maturityAge: 90,
    maxContributionYears: 57,
    rentAnnual: 240000,
    rentGrowth: 5,
  },
  gratuity: {
    type: 'gratuity',
    name: 'Gratuity',
    category: 'Retirement',
    currentValue: 0,
    contribution: 0,
    contributionMode: 'none',
    expectedReturn: 0,
    lockInYears: 5,
    currentAge: 33,
    maturityAge: 55,
    maxContributionYears: 22,
    basicDaMonthly: 180000,
    basicDaGrowth: 7,
    yearsOfService: 6,
    gratuityDivisor: 26,
    gratuityTaxExemption: 2000000,
  },
};

export const scenarioPresets = {
  conservative: {
    label: 'Conservative',
    returns: { epf: 8.15, nps: 8, ppf: 7.1, lic: 5, savings: 3, fd: 6.5, sukanya: 8, mutual_fund: 9, stocks: 10, etf: 8.5, real_estate_plot: 6, real_estate_flat: 5, rent_income: 4, gratuity: 0 },
  },
  moderate: {
    label: 'Moderate',
    returns: { epf: 8.15, nps: 9, ppf: 7.1, lic: 5.5, savings: 3.5, fd: 7, sukanya: 8.2, mutual_fund: 12, stocks: 13, etf: 11, real_estate_plot: 8, real_estate_flat: 6, rent_income: 5, gratuity: 0 },
  },
  aggressive: {
    label: 'Aggressive',
    returns: { epf: 8.15, nps: 10.5, ppf: 7.1, lic: 6, savings: 4, fd: 7.25, sukanya: 8.2, mutual_fund: 15, stocks: 16, etf: 13, real_estate_plot: 10, real_estate_flat: 8, rent_income: 6, gratuity: 0 },
  },
};

export const sampleInvestments = [
  { ...instrumentTemplates.epf, id: crypto.randomUUID() },
  { ...instrumentTemplates.mutual_fund, id: crypto.randomUUID(), contribution: 20000 },
  { ...instrumentTemplates.ppf, id: crypto.randomUUID(), contribution: 150000 },
  { ...instrumentTemplates.fd, id: crypto.randomUUID(), currentValue: 500000 },
  { ...instrumentTemplates.etf, id: crypto.randomUUID() },
  { ...instrumentTemplates.real_estate_flat, id: crypto.randomUUID() },
  { ...instrumentTemplates.gratuity, id: crypto.randomUUID() },
];
