import { z } from 'zod';

export const investmentSchema = z.object({
  name: z.string().min(2, 'Name is required'),
  category: z.string().min(2, 'Category is required'),
  currentValue: z.coerce.number().min(0),
  contribution: z.coerce.number().min(0),
  contributionMode: z.enum(['monthly', 'yearly', 'none']),
  expectedReturn: z.coerce.number().min(0).max(40),
  lockInYears: z.coerce.number().min(0).max(60),
  currentAge: z.coerce.number().min(0).max(100).optional(),
  maturityAge: z.coerce.number().min(0).max(100).optional(),
  maxContributionYears: z.coerce.number().min(0).max(80).optional(),
  salaryAnnual: z.coerce.number().min(0).optional(),
  salaryGrowth: z.coerce.number().min(0).max(30).optional(),
  basicDaMonthly: z.coerce.number().min(0).optional(),
  basicDaGrowth: z.coerce.number().min(0).max(30).optional(),
  yearsOfService: z.coerce.number().min(0).max(60).optional(),
  employerContributionRate: z.coerce.number().min(0).max(12).optional(),
  epsMonthlyContribution: z.coerce.number().min(0).max(1250).optional(),
  epsSalaryCapMonthly: z.coerce.number().min(0).optional(),
  epsPensionableSalaryMonthly: z.coerce.number().min(0).optional(),
  epsYearsOfService: z.coerce.number().min(0).max(60).optional(),
  epsPensionAge: z.coerce.number().min(50).max(70).optional(),
  epsEarlyPensionAge: z.coerce.number().min(50).max(58).optional(),
  epsMinimumPension: z.coerce.number().min(0).optional(),
  gratuityDivisor: z.coerce.number().refine((value) => [26, 30].includes(value), 'Use 26 or 30').optional(),
  gratuityTaxExemption: z.coerce.number().min(0).optional(),
  rentAnnual: z.coerce.number().min(0).optional(),
  rentGrowth: z.coerce.number().min(0).max(30).optional(),
  rentalYieldReinvestRate: z.coerce.number().min(0).max(30).optional(),
});
